CREATE TABLE DIFFUSION (
  idDIFFUSION INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  nomDIFFUSION VARCHAR(20)  NULL  ,
  libelleDIFFUSION VARCHAR(80)  NULL  ,
  adresseDIFFUSION VARCHAR(80)  NULL  ,
  codPostDIFFUSION VARCHAR(6)  NULL  ,
  communeDIFFUSION VARCHAR(30)  NULL  ,
  nomEtabDIFFUSION VARCHAR(60)  NULL    ,
PRIMARY KEY(idDIFFUSION));



CREATE TABLE CYCLE (
  idCYCLE INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  libelleCourtCYCLE VARCHAR(11)  NULL  ,
  libelleLongCYCLE VARCHAR(80)  NULL    ,
PRIMARY KEY(idCYCLE));



CREATE TABLE DIVISION (
  idDIVISION INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  libelleCourtDIVISION VARCHAR(20)  NULL  ,
  libelleLongDIVISION VARCHAR(80)  NULL    ,
PRIMARY KEY(idDIVISION));



CREATE TABLE UTI (
  idUTI INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  nomUTI VARCHAR(30)  NULL  ,
  prenomUTI VARCHAR(30)  NULL  ,
  telephoneUTI VARCHAR(10)  NULL  ,
  emailUTI VARCHAR(60)  NULL  ,
  loginUTI VARCHAR(20)  NULL  ,
  mdpUTI VARCHAR(255)  NULL  ,
  accesLDAPUTI VARCHAR(15)  NULL  ,
  sdaLDAPUTI INTEGER UNSIGNED  NULL  ,
  datemodifUTI DATETIME  NULL    ,
PRIMARY KEY(idUTI));



CREATE TABLE PROJET (
  idPROJET INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  nomPROJET VARCHAR(20)  NULL  ,
  libellePROJET VARCHAR(100)  NULL  ,
  contextePROJET VARCHAR(500)  NULL  ,
  indLocalPROJET SMALLINT UNSIGNED  NULL  ,
  indNationalPROJET SMALLINT UNSIGNED  NULL  ,
  indInterAcaPROJET SMALLINT UNSIGNED  NULL  ,
  dateDemandePROJET DATETIME  NULL  ,
  dateFinPROJET DATETIME  NULL  ,
  demPROJET LONGBLOB  NULL  ,
  mimedemPROJET VARCHAR(50)  NULL  ,
  sizedemPROJET INTEGER UNSIGNED  NULL  ,
  filenamedemPROJET VARCHAR(50)  NULL  ,
  extensiondemPROJET VARCHAR(4)  NULL  ,
  cdcPROJET LONGBLOB  NULL  ,
  mimecdcPROJET VARCHAR(50)  NULL  ,
  sizecdcPROJET INTEGER UNSIGNED  NULL  ,
  filenamecdcPROJET VARCHAR(50)  NULL  ,
  extensioncdcPROJET VARCHAR(4)  NULL  ,
  docPROJET LONGBLOB  NULL  ,
  mimedocPROJET VARCHAR(50)  NULL  ,
  sizedocPROJET INTEGER UNSIGNED  NULL  ,
  filenamedocPROJET VARCHAR(50)  NULL  ,
  extensiondocPROJET VARCHAR(4)  NULL    ,
PRIMARY KEY(idPROJET));



CREATE TABLE BASDON (
  idBASDON INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  nomBASDON VARCHAR(20)  NULL  ,
  libelleBASDON VARCHAR(100)  NULL  ,
  servBASDON VARCHAR(20)  NULL  ,
  emplBASDON VARCHAR(100)  NULL  ,
  chemShellBASDON VARCHAR(100)  NULL  ,
  loginBASDON VARCHAR(10)  NULL  ,
  mdpBASDON VARCHAR(128)  NULL    ,
PRIMARY KEY(idBASDON));



CREATE TABLE ADM (
  idADM INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  loginADM VARCHAR(20)  NULL  ,
  mdpADM VARCHAR(255)  NULL    ,
PRIMARY KEY(idADM));



CREATE TABLE MOA (
  idMOA INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  DIVISION_idDIVISION INTEGER UNSIGNED  NOT NULL  ,
  nomMOA VARCHAR(30)  NULL  ,
  prenomMOA VARCHAR(30)  NULL  ,
  emailMOA VARCHAR(80)  NULL  ,
  telFixeMOA VARCHAR(10)  NULL  ,
  telMobMOA VARCHAR(10)  NULL    ,
PRIMARY KEY(idMOA)  ,
INDEX MOA_FKIndex1(DIVISION_idDIVISION),
  FOREIGN KEY(DIVISION_idDIVISION)
    REFERENCES DIVISION(idDIVISION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE CONTACT (
  idCONTACT INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  DIFFUSION_idDIFFUSION INTEGER UNSIGNED  NOT NULL  ,
  nomCONTACT VARCHAR(30)  NULL  ,
  prenomCONTACT VARCHAR(30)  NULL  ,
  telephoneCONTACT VARCHAR(10)  NULL  ,
  emailCONTACT VARCHAR(80)  NULL  ,
  ssDomFoncCONTACT VARCHAR(80)  NULL  ,
  fonctionnelCONTACT BOOL  NULL  ,
  informatiqueCONTACT BOOL  NULL    ,
PRIMARY KEY(idCONTACT)  ,
INDEX CONTACT_FKIndex1(DIFFUSION_idDIFFUSION),
  FOREIGN KEY(DIFFUSION_idDIFFUSION)
    REFERENCES DIFFUSION(idDIFFUSION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE APPLI (
  idAPPLI INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  DIVISION_idDIVISION INTEGER UNSIGNED  NOT NULL  ,
  DIFFUSION_idDIFFUSION INTEGER UNSIGNED  NOT NULL  ,
  nomAPPLI VARCHAR(20)  NULL  ,
  libelleAPPLI VARCHAR(100)  NULL  ,
  urlPresAPPLI VARCHAR(300)  NULL  ,
  typeAPPLI INTEGER UNSIGNED  NULL  ,
  idRowAcaAPPLI VARCHAR(3)  NULL  ,
  prestataireAPPLI VARCHAR(200)  NULL  ,
  dateDiffusAPPLI DATETIME  NULL  ,
  dateDebutAPPLI DATETIME  NULL  ,
  dateFinAPPLI DATETIME  NULL  ,
  datePriseEnChargeAPPLI DATETIME  NULL  ,
  dateInstallationAPPLI DATETIME  NULL  ,
  dateMiseADispoAPPLI DATETIME  NULL  ,
  domFoncAPPLI VARCHAR(100)  NULL  ,
  loginAPPLI VARCHAR(10)  NULL  ,
  mdpAPPLI VARCHAR(128)  NULL    ,
PRIMARY KEY(idAPPLI)  ,
INDEX APPLI_FKIndex1(DIFFUSION_idDIFFUSION)  ,
INDEX APPLI_FKIndex2(DIVISION_idDIVISION),
  FOREIGN KEY(DIFFUSION_idDIFFUSION)
    REFERENCES DIFFUSION(idDIFFUSION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(DIVISION_idDIVISION)
    REFERENCES DIVISION(idDIVISION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE APPLI_has_BASDON (
  APPLI_idAPPLI INTEGER UNSIGNED  NOT NULL  ,
  BASDON_idBASDON INTEGER UNSIGNED  NOT NULL  ,
  indicAPPLI_has_BASDON SMALLINT UNSIGNED  NULL    ,
PRIMARY KEY(APPLI_idAPPLI, BASDON_idBASDON)  ,
INDEX APPLI_has_BASDON_FKIndex1(APPLI_idAPPLI)  ,
INDEX APPLI_has_BASDON_FKIndex2(BASDON_idBASDON),
  FOREIGN KEY(APPLI_idAPPLI)
    REFERENCES APPLI(idAPPLI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(BASDON_idBASDON)
    REFERENCES BASDON(idBASDON)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE APPLI_has_PROJET (
  APPLI_idAPPLI INTEGER UNSIGNED  NOT NULL  ,
  PROJET_idPROJET INTEGER UNSIGNED  NOT NULL    ,
PRIMARY KEY(APPLI_idAPPLI, PROJET_idPROJET)  ,
INDEX APPLI_has_PROJET_FKIndex1(APPLI_idAPPLI)  ,
INDEX APPLI_has_PROJET_FKIndex2(PROJET_idPROJET),
  FOREIGN KEY(APPLI_idAPPLI)
    REFERENCES APPLI(idAPPLI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PROJET_idPROJET)
    REFERENCES PROJET(idPROJET)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE APPLI_has_UTI (
  APPLI_idAPPLI INTEGER UNSIGNED  NOT NULL  ,
  UTI_idUTI INTEGER UNSIGNED  NOT NULL    ,
PRIMARY KEY(APPLI_idAPPLI, UTI_idUTI)  ,
INDEX APPLI_has_UTI_FKIndex1(APPLI_idAPPLI)  ,
INDEX APPLI_has_UTI_FKIndex2(UTI_idUTI),
  FOREIGN KEY(APPLI_idAPPLI)
    REFERENCES APPLI(idAPPLI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(UTI_idUTI)
    REFERENCES UTI(idUTI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE CONTACT_has_APPLI (
  CONTACT_idCONTACT INTEGER UNSIGNED  NOT NULL  ,
  APPLI_idAPPLI INTEGER UNSIGNED  NOT NULL    ,
PRIMARY KEY(CONTACT_idCONTACT, APPLI_idAPPLI)  ,
INDEX CONTACT_has_APPLI_FKIndex1(CONTACT_idCONTACT)  ,
INDEX CONTACT_has_APPLI_FKIndex2(APPLI_idAPPLI),
  FOREIGN KEY(CONTACT_idCONTACT)
    REFERENCES CONTACT(idCONTACT)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(APPLI_idAPPLI)
    REFERENCES APPLI(idAPPLI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE TRAITMAJ (
  idTRAITMAJ INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  APPLI_idAPPLI INTEGER UNSIGNED  NOT NULL  ,
  nomTRAITMAJ VARCHAR(20)  NULL  ,
  libelleTRAITMAJ VARCHAR(80)  NULL  ,
  servTRAITMAJ VARCHAR(20)  NULL  ,
  chemTRAITMAJ VARCHAR(100)  NULL  ,
  nomProgTRAITMAJ VARCHAR(30)  NULL  ,
  locCompRendTRAITMAJ VARCHAR(50)  NULL  ,
  crdTRAITMAJ LONGBLOB  NULL  ,
  mimecrdTRAITMAJ VARCHAR(50)  NULL  ,
  sizecrdTRAITMAJ INTEGER UNSIGNED  NULL  ,
  filenamecrdTRAITMAJ VARCHAR(50)  NULL  ,
  extensioncrdTRAITMAJ VARCHAR(4)  NULL    ,
PRIMARY KEY(idTRAITMAJ)  ,
INDEX TRAITMAJ_FKIndex1(APPLI_idAPPLI),
  FOREIGN KEY(APPLI_idAPPLI)
    REFERENCES APPLI(idAPPLI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE TRAITLOCAL (
  idTRAITLOCAL INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  APPLI_idAPPLI INTEGER UNSIGNED  NOT NULL  ,
  nomTRAITLOCAL VARCHAR(20)  NULL  ,
  libelleTRAITLOCAL VARCHAR(80)  NULL  ,
  servTRAITLOCAL VARCHAR(20)  NULL  ,
  chemTRAITLOCAL VARCHAR(100)  NULL  ,
  nomProgTRAITLOCAL VARCHAR(30)  NULL  ,
  phraseSQLTRAITLOCAL VARCHAR(1000)  NULL  ,
  datedemandeTRAITLOCAL DATETIME  NULL    ,
PRIMARY KEY(idTRAITLOCAL)  ,
INDEX TRAITLOCAL_FKIndex1(APPLI_idAPPLI),
  FOREIGN KEY(APPLI_idAPPLI)
    REFERENCES APPLI(idAPPLI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE CAMPAGNE (
  idCAMPAGNE INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  APPLI_idAPPLI INTEGER UNSIGNED  NOT NULL  ,
  libelleCAMPAGNE VARCHAR(100)  NULL  ,
  descriptifCAMPAGNE VARCHAR(500)  NULL    ,
PRIMARY KEY(idCAMPAGNE)  ,
INDEX CAMPAGNES_FKIndex1(APPLI_idAPPLI),
  FOREIGN KEY(APPLI_idAPPLI)
    REFERENCES APPLI(idAPPLI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE CALENDRIER (
  idCALENDRIER INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  APPLI_idAPPLI INTEGER UNSIGNED  NOT NULL  ,
  objetRDVCALENDRIER VARCHAR(80)  NULL  ,
  dateRDVCALENDRIER DATETIME  NULL  ,
  libelleCALENDRIER VARCHAR(200)  NULL  ,
  crdCALENDRIER LONGBLOB  NULL  ,
  mimecrdCALENDRIER VARCHAR(50)  NULL  ,
  sizecrdCALENDRIER INTEGER UNSIGNED  NULL  ,
  filenamecrdCALENDRIER VARCHAR(50)  NULL  ,
  extensioncrdCALENDRIER VARCHAR(4)  NULL    ,
PRIMARY KEY(idCALENDRIER)  ,
INDEX CALENDRIER_FKIndex1(APPLI_idAPPLI),
  FOREIGN KEY(APPLI_idAPPLI)
    REFERENCES APPLI(idAPPLI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE CAMPAGNECYCLE (
  idCAMPAGNECYCLE INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  CYCLE_idCYCLE INTEGER UNSIGNED  NOT NULL  ,
  CAMPAGNE_idCAMPAGNE INTEGER UNSIGNED  NOT NULL  ,
  datePrevOuvCAMPAGNECYCLE DATETIME  NULL  ,
  dateEffOuvCAMPAGNECYCLE DATETIME  NULL  ,
  datePrevFerCAMPAGNECYCLE DATETIME  NULL  ,
  dateEffFerCAMPAGNECYCLE DATETIME  NULL  ,
  datePrevFinCAMPAGNECYCLE DATETIME  NULL  ,
  dateEffFinCAMPAGNECYCLE DATETIME  NULL    ,
PRIMARY KEY(idCAMPAGNECYCLE)  ,
INDEX CAMPAGNECYCLE_FKIndex1(CAMPAGNE_idCAMPAGNE)  ,
INDEX CAMPAGNECYCLE_FKIndex2(CYCLE_idCYCLE),
  FOREIGN KEY(CAMPAGNE_idCAMPAGNE)
    REFERENCES CAMPAGNE(idCAMPAGNE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CYCLE_idCYCLE)
    REFERENCES CYCLE(idCYCLE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE PROCESSUS (
  idPROCESSUS INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  CAMPAGNE_idCAMPAGNE INTEGER UNSIGNED  NOT NULL  ,
  libellePROCESSUS VARCHAR(100)  NULL  ,
  descriptifPROCESSUS VARCHAR(500)  NULL    ,
PRIMARY KEY(idPROCESSUS)  ,
INDEX PROCESSUS_FKIndex1(CAMPAGNE_idCAMPAGNE),
  FOREIGN KEY(CAMPAGNE_idCAMPAGNE)
    REFERENCES CAMPAGNE(idCAMPAGNE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE TACHE (
  idTACHE INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  PROCESSUS_idPROCESSUS INTEGER UNSIGNED  NOT NULL  ,
  libelleTACHE VARCHAR(100)  NULL  ,
  descriptifTACHE VARCHAR(500)  NULL  ,
  synchroEntreeTACHE VARCHAR(500)  NULL  ,
  entreeTACHE VARCHAR(100)  NULL  ,
  sortieTACHE VARCHAR(100)  NULL  ,
  servTACHE VARCHAR(20)  NULL  ,
  nomTraitTACHE VARCHAR(20)  NULL  ,
  chemShellTACHE VARCHAR(100)  NULL    ,
PRIMARY KEY(idTACHE)  ,
INDEX TACHE_FKIndex1(PROCESSUS_idPROCESSUS),
  FOREIGN KEY(PROCESSUS_idPROCESSUS)
    REFERENCES PROCESSUS(idPROCESSUS)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE TACHECYCLE (
  idTACHECYCLE INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  CYCLE_idCYCLE INTEGER UNSIGNED  NOT NULL  ,
  TACHE_idTACHE INTEGER UNSIGNED  NOT NULL  ,
  datePrevOuvTACHECYCLE DATETIME  NULL  ,
  dateEffOuvTACHECYCLE DATETIME  NULL  ,
  datePrevFerTACHECYCLE DATETIME  NULL  ,
  dateEffFerTACHECYCLE DATETIME  NULL  ,
  datePrevFinTACHECYCLE DATETIME  NULL  ,
  dateEffFinTACHECYCLE DATETIME  NULL  ,
  contenuCompRendTACHECYCLE LONGBLOB  NULL  ,
  mimeCompRendTACHECYCLE VARCHAR(20)  NULL  ,
  sizeCompRendTACHECYCLE INTEGER UNSIGNED  NULL  ,
  filenameCompRendTACHECYCLE VARCHAR(50)  NULL  ,
  extensionCompRendTACHECYCLE VARCHAR(4)  NULL    ,
PRIMARY KEY(idTACHECYCLE)  ,
INDEX TACHECYCLE_FKIndex1(TACHE_idTACHE)  ,
INDEX TACHECYCLE_FKIndex2(CYCLE_idCYCLE),
  FOREIGN KEY(TACHE_idTACHE)
    REFERENCES TACHE(idTACHE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CYCLE_idCYCLE)
    REFERENCES CYCLE(idCYCLE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE PROCESSUSCYCLE (
  idPROCESSUSCYCLE INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  CYCLE_idCYCLE INTEGER UNSIGNED  NOT NULL  ,
  PROCESSUS_idPROCESSUS INTEGER UNSIGNED  NOT NULL  ,
  datePrevOuvPROCESSUSCYCLE DATETIME  NULL  ,
  dateEffOuvPROCESSUSCYCLE DATETIME  NULL  ,
  datePrevFerPROCESSUSCYCLE DATETIME  NULL  ,
  dateEffFerPROCESSUSCYCLE DATETIME  NULL  ,
  datePrevFinPROCESSUSCYCLE DATETIME  NULL  ,
  dateEffFinPROCESSUSCYCLE DATETIME  NULL    ,
PRIMARY KEY(idPROCESSUSCYCLE)  ,
INDEX PROCESSUSCYCLE_FKIndex1(PROCESSUS_idPROCESSUS)  ,
INDEX PROCESSUSCYCLE_FKIndex2(CYCLE_idCYCLE),
  FOREIGN KEY(PROCESSUS_idPROCESSUS)
    REFERENCES PROCESSUS(idPROCESSUS)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CYCLE_idCYCLE)
    REFERENCES CYCLE(idCYCLE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);




